/**
 * Home page content, mirroring the source design's `data-props`.
 *
 * Every home section reads exclusively from this module (plus `site.ts` for the
 * shared chrome), so swapping copy means editing here — never the markup. The
 * placeholder demo copy below is the source's own; replace it per project.
 */

export type Cta = {
  label: string;
  href: string;
};

export type Media = {
  src: string;
  alt: string;
};

export type Announcement = {
  text: string;
  cta: string;
  href: string;
};

export type FeatureItem = {
  title: string;
  body: string;
  cta: Cta;
  image: Media;
  /** Solid tint behind the screenshot frame (a literal colour, per the source). */
  tint: string;
};

export type Stat = {
  value: string;
  text: string;
};

export type Testimonial = {
  quote: string;
  name: string;
  role: string;
  /** Monogram shown in the avatar chip. */
  initials: string;
};

export type Faq = {
  question: string;
  answer: string;
};

export type PricingTier = {
  name: string;
  price: string;
  /** Suffix after the price, e.g. "/mo". */
  period: string;
  blurb: string;
  features: string[];
  popular: boolean;
  cta: Cta;
};

export type HomeConfig = {
  seo: { description: string };
  announcement: Announcement;
  showAnnouncement: boolean;
  showLogos: boolean;
  hero: {
    headline: string;
    subheadline: string;
    primaryCta: Cta;
    secondaryCta: Cta;
    image: Media;
    /** Solid colour of the product-shot frame (a literal colour, per the source). */
    frameColor: string;
  };
  logos: string[];
  features: {
    eyebrow: string;
    headline: string;
    subheadline: string;
    items: FeatureItem[];
  };
  stats: {
    eyebrow: string;
    headline: string;
    subheadline: string;
    items: Stat[];
  };
  testimonials: {
    headline: string;
    subheadline: string;
    items: Testimonial[];
  };
  faqs: {
    headline: string;
    items: Faq[];
  };
  pricing: {
    headline: string;
    tiers: PricingTier[];
  };
  cta: {
    headline: string;
    subheadline: string;
    primaryCta: Cta;
    secondaryCta: Cta;
  };
};

const startTrial: Cta = { label: "Start free trial", href: "#start" };
const seeHow: Cta = { label: "See how it works", href: "#how" };

export const home: HomeConfig = {
  seo: {
    description:
      "Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal — even if it was generated by a bot.",
  },

  announcement: {
    text: "Oatmeal raises $80M Series A funding",
    cta: "Learn more",
    href: "#news",
  },
  showAnnouncement: true,
  showLogos: true,

  hero: {
    headline: "Customer support that feels like a conversation.",
    subheadline:
      "Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal — even if it was generated by a bot.",
    primaryCta: startTrial,
    secondaryCta: seeHow,
    image: { src: "/uploads/pasted-1784247258125-0.png", alt: "Oatmeal product screenshot" },
    frameColor: "#5F6B4E",
  },

  logos: ["Quirk", "Concise.", "Anomaly", "PINE LABS", "Orbital", "ARTIFACT"],

  features: {
    eyebrow: "Powerful features",
    headline: "Everything you need to deliver personal, organized, and delightful support.",
    subheadline:
      "Work smarter, reply faster, and keep every customer conversation right where it belongs — in one simple inbox.",
    items: [
      {
        title: "Shared Inbox",
        body: "Keep every customer conversation in one clean, collaborative inbox. A single source of truth is much easier to ignore.",
        cta: seeHow,
        image: { src: "/uploads/pasted-1784247251805-0.png", alt: "Shared inbox screenshot" },
        tint: "#9E7B86",
      },
      {
        title: "Inbox Agent",
        body: "Get valuable context without having to read through your customer's long, angry email thread.",
        cta: seeHow,
        image: { src: "/uploads/pasted-1784247258125-0.png", alt: "Inbox agent screenshot" },
        tint: "#7A8A9C",
      },
    ],
  },

  stats: {
    eyebrow: "Built for scale",
    headline: "The inbox powering customer conversations everywhere.",
    subheadline:
      "Oatmeal helps teams deliver personal, organized, and fast customer support across the world. From small startups to enterprise teams, we process millions of messages each month.",
    items: [
      { value: "2M+", text: "Emails manually processed every week across thousands of teams." },
      { value: "99.98%", text: "Uptime — because your customers never stop complaining." },
    ],
  },

  testimonials: {
    headline: "What our customers are saying",
    subheadline:
      "We've given these customers a significant discount in exchange for their honest reviews.",
    items: [
      {
        quote:
          "Oatmeal has completely transformed our customer support operations. To be fair, we weren't doing any customer support at all so the bar was pretty low.",
        name: "Jordan Rogers",
        role: "Founder at Anomaly",
        initials: "JR",
      },
      {
        quote:
          "We use Oatmeal's automation features to make cancellation requests disappear into a black hole, improving our retention rates by over 300%.",
        name: "Lynn Marshall",
        role: "Founder at Pine Labs",
        initials: "LM",
      },
      {
        quote:
          "I've been using the spare time that Oatmeal has freed up to work not just one, but two other jobs, all while hitting my core KPIs. My bosses have no idea.",
        name: "Rajat Singh",
        role: "Head of Support at Concise",
        initials: "RS",
      },
      {
        quote:
          "Oatmeal has given us key insights into how much our customers absolutely hate using our product and how we can improve it to stop them from leaving us.",
        name: "John Walters",
        role: "CFO at Orbital",
        initials: "JW",
      },
      {
        quote:
          "As a solo founder, Oatmeal has been a lifesaver. It makes it look like Loeply is an actual company with multiple employees, when in reality it's just me and an AI.",
        name: "Noah Gold",
        role: "CEO at Loeply",
        initials: "NG",
      },
      {
        quote:
          "Thanks to Oatmeal, we've managed to cut our support costs in half by laying off dozens of employees, while still improving response times and customer satisfaction.",
        name: "Mark Levinson",
        role: "COO at Quirk",
        initials: "ML",
      },
    ],
  },

  faqs: {
    headline: "Questions & Answers",
    items: [
      {
        question: "Do I need a credit card to start the free trial?",
        answer:
          "No. Start your 14-day trial with just an email address — we'll only ask for a card if you decide to stick around once it's over.",
      },
      {
        question: "Can my whole team use the same inbox?",
        answer:
          "Absolutely — that's the whole point. Invite unlimited teammates on Growth and above and collaborate on every conversation without stepping on each other's toes.",
      },
      {
        question: "Is the AI agent actually a bunch of people in India?",
        answer:
          "We can neither confirm nor deny. What we can promise is that every reply feels personal, arrives fast, and passes for a human every single time.",
      },
      {
        question: "Does Oatmeal replace my email client?",
        answer:
          "For customer support, yes. Oatmeal becomes the shared inbox for every customer conversation, so your personal email can go back to being just for newsletters.",
      },
    ],
  },

  pricing: {
    headline: "Pricing to fit your business needs.",
    tiers: [
      {
        name: "Starter",
        price: "$12",
        period: "/mo",
        blurb: "Small teams getting started with shared inboxes",
        popular: false,
        features: [
          "Shared inbox for up to 2 mailboxes",
          "Tagging & assignment",
          "Private notes",
          "Automatic replies",
          "Email support",
        ],
        cta: startTrial,
      },
      {
        name: "Growth",
        price: "$49",
        period: "/mo",
        blurb: "Growing teams needing collaboration and insights",
        popular: true,
        features: [
          "Everything in Starter",
          "Inbox Agent",
          "Unlimited mailboxes",
          "Collision detection",
          "Snippets and templates",
          "Reporting dashboard",
          "Slack integration",
        ],
        cta: startTrial,
      },
      {
        name: "Pro",
        price: "$299",
        period: "/mo",
        blurb: "Support-focused organizations and larger teams",
        popular: false,
        features: [
          "Everything in Growth",
          "Automation engine",
          "API access",
          "SLA tracking",
          "Priority support",
          "Onboarding assistance",
        ],
        cta: startTrial,
      },
    ],
  },

  cta: {
    headline: "Ready to make customer support feel simple again?",
    subheadline:
      "Join hundreds of teams using Oatmeal to deliver faster, friendlier email support.",
    primaryCta: startTrial,
    secondaryCta: { label: "Book a demo", href: "#demo" },
  },
};
