/**
 * Home page content. Section markup reads exclusively from this module (plus
 * `shared.ts` and `pricing.ts`), so re-theming the home page means editing here.
 */

import type { Cta, Placement, Testimonial, Wallpaper } from "./shared";

export type Announcement = {
  text: string;
  cta: string;
  href: string;
};

export type FeatureItem = {
  headline: string;
  subheadline: string;
  cta: Cta;
  /** Base screenshot URL; crop variants are appended by the section. */
  screenshot: string;
  wallpaper: Wallpaper;
  placement: Placement;
};

export type HomeConfig = {
  seo: { title?: string; description: string };
  hero: {
    announcement: Announcement;
    headline: string;
    subheadline: string;
    primaryCta: Cta;
    secondaryCta: Cta;
    /** Base screenshot URL; crop variants are appended by the section. */
    screenshot: string;
  };
  features: {
    eyebrow: string;
    headline: string;
    subheadline: string;
    items: FeatureItem[];
  };
  testimonials: {
    headline: string;
    subheadline: string;
    items: Testimonial[];
  };
  pricing: { headline: string };
  cta: {
    headline: string;
    subheadline: string;
    primaryCta: Cta;
    secondaryCta: Cta;
  };
};

export const home: HomeConfig = {
  seo: {
    description:
      "Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal — even if it was generated by a bot.",
  },

  hero: {
    announcement: {
      text: "Oatmeal raises 80M Series A funding",
      cta: "Learn more",
      href: "#",
    },
    headline: "Customer support that feels like a conversation.",
    subheadline:
      "Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal — even if it was generated by a bot.",
    primaryCta: { label: "Start free trial", href: "#" },
    secondaryCta: { label: "See how it works", href: "#" },
    screenshot: "https://assets.tailwindplus.com/screenshots/1.webp",
  },

  features: {
    eyebrow: "Powerful features",
    headline: "Everything you need to deliver personal, organized, and delightful support.",
    subheadline:
      "Work smarter, reply faster, and keep every customer conversation right where it belongs — in one simple inbox.",
    items: [
      {
        headline: "Shared Inbox",
        subheadline:
          "Keep every customer conversation in one clean, collaborative inbox. A single source of truth is much easier to ignore.",
        cta: { label: "See how it works", href: "#" },
        screenshot: "https://assets.tailwindplus.com/screenshots/1.webp",
        wallpaper: "purple",
        placement: "bottom-right",
      },
      {
        headline: "Inbox Agent",
        subheadline:
          "Get valuable context without having to read through your customer's long, angry email thread.",
        cta: { label: "See how it works", href: "#" },
        screenshot: "https://assets.tailwindplus.com/screenshots/1.webp",
        wallpaper: "blue",
        placement: "bottom-left",
      },
    ],
  },

  testimonials: {
    headline: "What our customers are saying",
    subheadline:
      "We've given these customers a significant discount in exchange for their honest reviews.",
    items: [
      {
        quote:
          "Oatmeal has completely transformed our customer support operations. To be fair, we weren't doing any customer support at all so the bar was pretty low.",
        avatar: "https://assets.tailwindplus.com/avatars/10.webp?size=160",
        name: "Jordan Rogers",
        byline: "Founder at Anomaly",
      },
      {
        quote:
          "We use Oatmeal's automation features to make cancellation requests disappear into a black hole, improving our retention rates by over 300%.",
        avatar: "https://assets.tailwindplus.com/avatars/15.webp?size=160",
        name: "Lynn Marshall",
        byline: "Founder at Pine Labs",
      },
      {
        quote:
          "I've been using the spare time that Oatmeal has freed up to work not just one, but two other jobs, all while hitting my core KPIs. My bosses have no idea.",
        avatar: "https://assets.tailwindplus.com/avatars/13.webp?size=160",
        name: "Rajat Singh",
        byline: "Head of Support at Concise",
      },
      {
        quote:
          "Oatmeal has given us key insights into how much our customers absolutely hate using our product and how we can improve it to stop them from leaving us.",
        avatar: "https://assets.tailwindplus.com/avatars/12.webp?size=160",
        name: "John Walters",
        byline: "CPO at Orbital",
      },
      {
        quote:
          "As a solo founder, Oatmeal has been a lifesaver. It makes it look like Looply is an actual company with multiple employees, when in reality it's just me and an AI.",
        avatar: "https://assets.tailwindplus.com/avatars/11.webp?size=160",
        name: "Noah Gold",
        byline: "CEO at Looply",
      },
      {
        quote:
          "Thanks to Oatmeal, we've managed to cut our support costs in half by laying off dozens of employees, while still improving response times and customer satisfaction.",
        avatar: "https://assets.tailwindplus.com/avatars/14.webp?size=160",
        name: "Mark Levinson",
        byline: "COO at Quirk",
      },
    ],
  },

  pricing: { headline: "Pricing to fit your business needs." },

  cta: {
    headline: "Ready to make customer support feel simple again?",
    subheadline:
      "Join hundreds of teams using Oatmeal to deliver faster, friendlier email support — using a massive network of low wage workers stationed around the globe",
    primaryCta: { label: "Start free trial", href: "#" },
    secondaryCta: { label: "Book a demo", href: "#" },
  },
};
