/**
 * Brand, navigation, footer and SEO defaults — the site "chrome" shared by
 * every page.
 *
 * This file, its sibling `home.ts`, and the MDX in `src/content` are the only
 * places you should need to edit to re-content this site for a new project.
 * Components read from here — never hardcode copy into markup.
 */

export type NavLink = {
  label: string;
  href: string;
};

export type FooterColumn = {
  title: string;
  links: NavLink[];
};

/** Keys map to the inline icons wired up in `src/components/sections/Footer.astro`. */
export type SocialPlatform = "x" | "github" | "youtube";

export type SocialLink = {
  platform: SocialPlatform;
  /** Accessible name for the icon-only link. */
  name: string;
  href: string;
};

export type SiteConfig = {
  /** The brand name — rendered in the nav wordmark, footer and SEO. */
  name: string;
  /** Logo URL used only for SEO/JSON-LD (the visible wordmark is text). */
  logo: { light: string; dark: string; alt: string; width: number; height: number };
  nav: NavLink[];
  actions: { login: NavLink; getStarted: NavLink };
  footer: {
    newsletter: { headline: string; body: string; placeholder: string };
    columns: FooterColumn[];
    /** `%s` is replaced with the brand name. */
    fineprint: string;
  };
  social: SocialLink[];
  notFound: { title: string; headline: string; subheadline: string; cta: NavLink };
  seo: {
    /** `%s` is replaced with the per-page title. */
    titleTemplate: string;
    defaultTitle: string;
    defaultDescription: string;
    /** Absolute URL or site-relative path. 1200x630. */
    defaultImage: string;
    twitterHandle: string;
    locale: string;
  };
};

export const site: SiteConfig = {
  name: "Oatmeal",

  logo: {
    light: "/favicon.svg",
    dark: "/favicon.svg",
    alt: "Oatmeal",
    width: 32,
    height: 32,
  },

  nav: [
    { label: "Pricing", href: "#pricing" },
    { label: "About", href: "#about" },
    { label: "Docs", href: "#docs" },
  ],

  actions: {
    login: { label: "Log in", href: "#login" },
    getStarted: { label: "Get started", href: "#start" },
  },

  footer: {
    newsletter: {
      headline: "Stay in the loop",
      body: "Get customer support tips, product updates and customer scores that you can archive as soon as they arrive.",
      placeholder: "Email",
    },
    columns: [
      {
        title: "Product",
        links: [
          { label: "Features", href: "#features" },
          { label: "Pricing", href: "#pricing" },
          { label: "Integrations", href: "#" },
        ],
      },
      {
        title: "Company",
        links: [
          { label: "About", href: "#about" },
          { label: "Careers", href: "#" },
          { label: "Blog", href: "#" },
          { label: "Press Kit", href: "#" },
        ],
      },
      {
        title: "Resources",
        links: [
          { label: "Help Center", href: "#" },
          { label: "API Docs", href: "#" },
          { label: "Status", href: "#" },
          { label: "Contact", href: "#" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Privacy Policy", href: "/privacy" },
          { label: "Terms of Service", href: "#" },
          { label: "Security", href: "#" },
        ],
      },
    ],
    fineprint: "© 2025 %s, Inc.",
  },

  social: [
    { platform: "x", name: "X", href: "https://x.com" },
    { platform: "github", name: "GitHub", href: "https://github.com" },
    { platform: "youtube", name: "YouTube", href: "https://www.youtube.com" },
  ],

  notFound: {
    title: "Page not found",
    headline: "Page not found",
    subheadline: "Sorry, but the page you were looking for could not be found.",
    cta: { label: "Go back home", href: "/" },
  },

  seo: {
    titleTemplate: "%s — Oatmeal",
    defaultTitle: "Oatmeal — Customer support that feels like a conversation",
    defaultDescription:
      "Simplify your shared inbox, collaborate effortlessly, and give every customer a reply that feels personal — even if it was generated by a bot.",
    defaultImage: "/og.png",
    twitterHandle: "@oatmeal",
    locale: "en_US",
  },
};
